#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

apigen_image=ghcr.io/turbopuffer/turbopuffer-apigen:e7c9ed95c7a503403b2707f141356c981c3b37a6

apigen() {
    if [[ "$TURBOPUFFER_DEV_APIGEN" ]]; then
        cargo run --manifest-path=../turbopuffer-apigen/Cargo.toml "$@"
    else
        docker run -v "$(pwd):/work" "$apigen_image" "$@"
    fi
}

echo "==> Generating code"
apigen go > custom_types.go
gofmt -s -w custom_types.go
