#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

api_gen_image=ghcr.io/turbopuffer/turbopuffer-apigen:71dff63fff6400a94ec9c41f731513669e1060d4

echo "==> Generating code"
docker run -v "$(pwd):/work" "$api_gen_image" go > custom_types.go
