#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Checking for outdated supplemental generated code"
scripts/gen
if ! git diff --exit-code; then
    echo "error: supplemental generated code is out of date" >&2
    echo " hint: run \`scripts/gen\` to regenerate the code" >&2
    exit 1
fi

echo "==> Checking for misformatted code"
scripts/format
if ! git diff --exit-code; then
    echo "error: code formatting is incorrect" >&2
    echo " hint: run \`scripts/format\` to fix the formatting" >&2
    exit 1
fi

echo "==> Running Go build"
go build ./...

echo "==> Checking tests compile"
go test -run=^$ ./...
